package ayman.djangogenerator;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class DjangoFormsetGenerator {
    
    public static String generateViewsCode(JSONObject projectJson) throws JSONException {
        StringBuilder code = new StringBuilder();
        
        code.append("# views.py - Generated with Django Formsets\n");
        code.append("# Auto-generated by Django Generator Android App\n");
        code.append("\n");
        code.append("from django.shortcuts import render, redirect, get_object_or_404\n");
        code.append("from django.forms import inlineformset_factory\n");
        code.append("from django.contrib import messages\n");
        code.append("from django.urls import reverse_lazy\n");
        code.append("from django.views.generic import CreateView, UpdateView, ListView, DeleteView\n");
        code.append("from .models import *\n");
        code.append("from .forms import *\n");
        code.append("\n");
        
        if (projectJson.has("formsets")) {
            JSONArray formsets = projectJson.getJSONArray("formsets");
            
            // Group formsets by parent model
            Map<String, List<JSONObject>> formsetsByParent = new HashMap<>();
            
            for (int i = 0; i < formsets.length(); i++) {
                JSONObject formset = formsets.getJSONObject(i);
                String parentModelName = formset.getString("parent_model_name");
                
                if (!formsetsByParent.containsKey(parentModelName)) {
                    formsetsByParent.put(parentModelName, new ArrayList<JSONObject>());
                }
                formsetsByParent.get(parentModelName).add(formset);
            }
            
            // Generate code for each parent model
            for (Map.Entry<String, List<JSONObject>> entry : formsetsByParent.entrySet()) {
                String parentModelName = entry.getKey();
                List<JSONObject> parentFormsets = entry.getValue();
                
                code.append("# ============ ").append(parentModelName)
                    .append(" with ").append(parentFormsets.size())
                    .append(" inline formsets ============\n\n");
                
                // CREATE VIEW
                code.append("def create_").append(parentModelName.toLowerCase()).append("(request):\n");
                code.append("    \"\"\"\n");
                code.append("    Create new ").append(parentModelName).append(" with related data\n");
                code.append("    Includes: ");
                for (int i = 0; i < parentFormsets.size(); i++) {
                    JSONObject formset = parentFormsets.get(i);
                    code.append(formset.getString("child_model_name"));
                    if (i < parentFormsets.size() - 1) code.append(", ");
                }
                code.append("\n");
                code.append("    \"\"\"\n");
                code.append("\n");
                
                // Create formset factories
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    String prefix = formset.optString("prefix", childModelName.toLowerCase());
                    int extra = formset.optInt("extra_fields", 1);
                    boolean canDelete = formset.optBoolean("can_delete", true);
                    
                    code.append("    ").append(childModelName).append("FormSet = inlineformset_factory(\n");
                    code.append("        ").append(parentModelName).append(",\n");
                    code.append("        ").append(childModelName).append(",\n");
                    code.append("        form=").append(childModelName).append("Form,\n");
                    code.append("        fields='__all__',\n");
                    code.append("        extra=").append(extra).append(",\n");
                    code.append("        can_delete=").append(canDelete ? "True" : "False").append("\n");
                    code.append("    )\n");
                }
                code.append("\n");
                
                // POST logic
                code.append("    if request.method == 'POST':\n");
                code.append("        form = ").append(parentModelName).append("Form(request.POST)\n");
                
                // Initialize formsets in POST
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    String prefix = formset.optString("prefix", childModelName.toLowerCase());
                    code.append("        ").append(childModelName.toLowerCase()).append("_formset = ");
                    code.append(childModelName).append("FormSet(request.POST, prefix='").append(prefix).append("')\n");
                }
                code.append("\n");
                
                // Validation
                code.append("        # Validate all forms\n");
                code.append("        is_valid = form.is_valid()\n");
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    code.append("        is_valid = is_valid and ").append(childModelName.toLowerCase())
                        .append("_formset.is_valid()\n");
                }
                code.append("\n");
                code.append("        if is_valid:\n");
                code.append("            # Save parent object first\n");
                code.append("            parent_obj = form.save()\n");
                code.append("\n");
                
                // Save each formset
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    code.append("            # Save ").append(childModelName).append(" records\n");
                    code.append("            ").append(childModelName.toLowerCase()).append("_formset.instance = parent_obj\n");
                    code.append("            ").append(childModelName.toLowerCase()).append("_formset.save()\n");
                }
                code.append("\n");
                code.append("            messages.success(request, f'").append(parentModelName)
                    .append(" \\\"{parent_obj}\\\" was created successfully!')\n");
                code.append("            return redirect('").append(parentModelName.toLowerCase()).append("_list')\n");
                code.append("        else:\n");
                code.append("            messages.error(request, 'Please correct the errors below.')\n");
                code.append("    else:\n");
                code.append("        form = ").append(parentModelName).append("Form()\n");
                
                // Initialize formsets in GET
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    String prefix = formset.optString("prefix", childModelName.toLowerCase());
                    code.append("        ").append(childModelName.toLowerCase()).append("_formset = ");
                    code.append(childModelName).append("FormSet(prefix='").append(prefix).append("')\n");
                }
                code.append("\n");
                
                // Context
                code.append("    context = {\n");
                code.append("        'form': form,\n");
                code.append("        'title': 'Create New ").append(parentModelName).append("',\n");
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    code.append("        '").append(childModelName.toLowerCase()).append("_formset': ");
                    code.append(childModelName.toLowerCase()).append("_formset,\n");
                }
                code.append("        'formsets_count': ").append(parentFormsets.size()).append(",\n");
                code.append("    }\n");
                code.append("    \n");
                code.append("    return render(request, '").append(parentModelName.toLowerCase()).append("/form.html', context)\n");
                code.append("\n\n");
                
                // UPDATE VIEW
                code.append("def update_").append(parentModelName.toLowerCase()).append("(request, pk):\n");
                code.append("    \"\"\"\n");
                code.append("    Update existing ").append(parentModelName).append(" with related data\n");
                code.append("    \"\"\"\n");
                code.append("    parent_obj = get_object_or_404(").append(parentModelName).append(", pk=pk)\n");
                code.append("\n");
                
                // Create formset factories for update (with extra=1)
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    String prefix = formset.optString("prefix", childModelName.toLowerCase());
                    boolean canDelete = formset.optBoolean("can_delete", true);
                    
                    code.append("    ").append(childModelName).append("FormSet = inlineformset_factory(\n");
                    code.append("        ").append(parentModelName).append(",\n");
                    code.append("        ").append(childModelName).append(",\n");
                    code.append("        form=").append(childModelName).append("Form,\n");
                    code.append("        fields='__all__',\n");
                    code.append("        extra=1,\n");
                    code.append("        can_delete=").append(canDelete ? "True" : "False").append("\n");
                    code.append("    )\n");
                }
                code.append("\n");
                
                // POST logic for update
                code.append("    if request.method == 'POST':\n");
                code.append("        form = ").append(parentModelName).append("Form(request.POST, instance=parent_obj)\n");
                
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    String prefix = formset.optString("prefix", childModelName.toLowerCase());
                    code.append("        ").append(childModelName.toLowerCase()).append("_formset = ");
                    code.append(childModelName).append("FormSet(request.POST, instance=parent_obj, prefix='")
                        .append(prefix).append("')\n");
                }
                code.append("\n");
                
                // Validation for update
                code.append("        is_valid = form.is_valid()\n");
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    code.append("        is_valid = is_valid and ").append(childModelName.toLowerCase())
                        .append("_formset.is_valid()\n");
                }
                code.append("\n");
                code.append("        if is_valid:\n");
                code.append("            form.save()\n");
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    code.append("            ").append(childModelName.toLowerCase()).append("_formset.save()\n");
                }
                code.append("            messages.success(request, f'").append(parentModelName)
                    .append(" \\\"{parent_obj}\\\" was updated successfully!')\n");
                code.append("            return redirect('").append(parentModelName.toLowerCase()).append("_list')\n");
                code.append("    else:\n");
                code.append("        form = ").append(parentModelName).append("Form(instance=parent_obj)\n");
                
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    String prefix = formset.optString("prefix", childModelName.toLowerCase());
                    code.append("        ").append(childModelName.toLowerCase()).append("_formset = ");
                    code.append(childModelName).append("FormSet(instance=parent_obj, prefix='")
                        .append(prefix).append("')\n");
                }
                code.append("\n");
                
                // Context for update
                code.append("    context = {\n");
                code.append("        'form': form,\n");
                code.append("        'title': 'Update ").append(parentModelName).append("',\n");
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    code.append("        '").append(childModelName.toLowerCase()).append("_formset': ");
                    code.append(childModelName.toLowerCase()).append("_formset,\n");
                }
                code.append("        'parent_obj': parent_obj,\n");
                code.append("        'formsets_count': ").append(parentFormsets.size()).append(",\n");
                code.append("    }\n");
                code.append("    \n");
                code.append("    return render(request, '").append(parentModelName.toLowerCase()).append("/form.html', context)\n");
                code.append("\n\n");
            }
        } else {
            code.append("# No formsets configured for this project\n");
            code.append("# Use the admin panel or create formsets in the Android app\n");
        }
        
        return code.toString();
    }
    
    public static String generateFormsCode(JSONObject projectJson) throws JSONException {
        StringBuilder code = new StringBuilder();
        
        code.append("# forms.py - Generated Forms with Inline Formsets\n");
        code.append("# Auto-generated by Django Generator Android App\n");
        code.append("\n");
        code.append("from django import forms\n");
        code.append("from django.forms import inlineformset_factory\n");
        code.append("from .models import *\n");
        code.append("\n");
        
        Set<String> generatedForms = new HashSet<>();
        
        if (projectJson.has("formsets")) {
            JSONArray formsets = projectJson.getJSONArray("formsets");
            
            // Generate forms for all models in formsets
            for (int i = 0; i < formsets.length(); i++) {
                JSONObject formset = formsets.getJSONObject(i);
                
                String parentModelName = formset.getString("parent_model_name");
                String childModelName = formset.getString("child_model_name");
                
                // Parent form
                if (!generatedForms.contains(parentModelName)) {
                    code.append("class ").append(parentModelName).append("Form(forms.ModelForm):\n");
                    code.append("    class Meta:\n");
                    code.append("        model = ").append(parentModelName).append("\n");
                    code.append("        fields = '__all__'\n");
                    code.append("        \n");
                    code.append("        widgets = {\n");
                    code.append("            # Add custom widgets here\n");
                    code.append("            # Example:\n");
                    code.append("            # 'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter name'}),\n");
                    code.append("            # 'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),\n");
                    code.append("        }\n");
                    code.append("        \n");
                    code.append("        labels = {\n");
                    code.append("            # Customize field labels\n");
                    code.append("        }\n");
                    code.append("        \n");
                    code.append("        help_texts = {\n");
                    code.append("            # Add help text\n");
                    code.append("        }\n");
                    code.append("        \n");
                    code.append("        error_messages = {\n");
                    code.append("            # Custom error messages\n");
                    code.append("        }\n");
                    code.append("\n");
                    generatedForms.add(parentModelName);
                }
                
                // Child form
                if (!generatedForms.contains(childModelName)) {
                    code.append("class ").append(childModelName).append("Form(forms.ModelForm):\n");
                    code.append("    class Meta:\n");
                    code.append("        model = ").append(childModelName).append("\n");
                    code.append("        fields = '__all__'\n");
                    code.append("        \n");
                    code.append("        widgets = {\n");
                    code.append("            # Add custom widgets for ").append(childModelName).append("\n");
                    code.append("        }\n");
                    code.append("\n");
                    generatedForms.add(childModelName);
                }
            }
            
            code.append("\n");
            code.append("# ============ Inline Formsets Factories ============\n");
            code.append("\n");
            
            // Generate formset factories
            for (int i = 0; i < formsets.length(); i++) {
                JSONObject formset = formsets.getJSONObject(i);
                
                String parentModelName = formset.getString("parent_model_name");
                String childModelName = formset.getString("child_model_name");
                int extraFields = formset.optInt("extra_fields", 1);
                boolean canDelete = formset.optBoolean("can_delete", true);
                String prefix = formset.optString("prefix", childModelName.toLowerCase());
                
                code.append(childModelName).append("FormSet = inlineformset_factory(\n");
                code.append("    ").append(parentModelName).append(",  # Parent model\n");
                code.append("    ").append(childModelName).append(",  # Child model\n");
                code.append("    form=").append(childModelName).append("Form,  # Form class\n");
                code.append("    fields='__all__',  # Or specify fields: ['field1', 'field2']\n");
                code.append("    extra=").append(extraFields).append(",  # Number of empty forms\n");
                code.append("    can_delete=").append(canDelete ? "True" : "False").append(",  # Allow deletion\n");
                code.append("    max_num=").append(formset.optInt("max_num", 10)).append(",  # Maximum forms\n");
                code.append("    validate_max=").append(formset.optInt("max_num", 10) > 0 ? "True" : "False").append(",  # Validate max\n");
                code.append("    prefix='").append(prefix).append("'  # Form prefix\n");
                code.append(")\n");
                code.append("\n");
            }
        }
        
        return code.toString();
    }
    
    public static String generateTemplateCode(JSONObject projectJson) throws JSONException {
        StringBuilder html = new StringBuilder();
        
        html.append("<!-- templates/includes/formset_template.html -->\n");
        html.append("<!-- Auto-generated formset template -->\n");
        html.append("<!-- Include this template in your form pages -->\n");
        html.append("\n");
        
        if (projectJson.has("formsets")) {
            JSONArray formsets = projectJson.getJSONArray("formsets");
            
            // Group by parent model
            Map<String, List<JSONObject>> formsetsByParent = new HashMap<>();
            
            for (int i = 0; i < formsets.length(); i++) {
                JSONObject formset = formsets.getJSONObject(i);
                String parentModelName = formset.getString("parent_model_name");
                
                if (!formsetsByParent.containsKey(parentModelName)) {
                    formsetsByParent.put(parentModelName, new ArrayList<JSONObject>());
                }
                formsetsByParent.get(parentModelName).add(formset);
            }
            
            // Generate template for each parent model
            for (Map.Entry<String, List<JSONObject>> entry : formsetsByParent.entrySet()) {
                String parentModelName = entry.getKey();
                List<JSONObject> parentFormsets = entry.getValue();
                
                html.append("<!-- ============ Template for ").append(parentModelName)
                    .append(" ============ -->\n");
                html.append("<!-- Save as: templates/").append(parentModelName.toLowerCase()).append("/form.html -->\n");
                html.append("\n");
                html.append("{% extends 'base.html' %}\n");
                html.append("{% load crispy_forms_tags %}\n");
                html.append("{% load static %}\n");
                html.append("\n");
                html.append("{% block title %}{{ title }}{% endblock %}\n");
                html.append("\n");
                html.append("{% block content %}\n");
                html.append("<div class=\"container mt-4\">\n");
                html.append("    <div class=\"row\">\n");
                html.append("        <div class=\"col-md-12\">\n");
                html.append("            <div class=\"card\">\n");
                html.append("                <div class=\"card-header\">\n");
                html.append("                    <h3 class=\"card-title\">{{ title }}</h3>\n");
                html.append("                </div>\n");
                html.append("                <div class=\"card-body\">\n");
                html.append("                    <form method=\"post\" id=\"multi-formset-form\" enctype=\"multipart/form-data\">\n");
                html.append("                        {% csrf_token %}\n");
                html.append("\n");
                html.append("                        <!-- Main Form -->\n");
                html.append("                        <div class=\"main-form-section mb-4\">\n");
                html.append("                            <h4 class=\"section-title\">").append(parentModelName).append(" Details</h4>\n");
                html.append("                            <div class=\"form-container\">\n");
                html.append("                                {{ form|crispy }}\n");
                html.append("                            </div>\n");
                html.append("                        </div>\n");
                html.append("\n");
                
                // Generate section for each formset
                for (int i = 0; i < parentFormsets.size(); i++) {
                    JSONObject formset = parentFormsets.get(i);
                    String childModelName = formset.getString("child_model_name");
                    String formsetVar = childModelName.toLowerCase() + "_formset";
                    
                    html.append("                        <!-- ").append(childModelName).append(" Section -->\n");
                    html.append("                        <div class=\"formset-section mb-4\">\n");
                    html.append("                            <div class=\"section-header d-flex justify-content-between align-items-center mb-3\">\n");
                    html.append("                                <h4 class=\"section-title\">").append(childModelName).append("</h4>\n");
                    html.append("                                <button type=\"button\" class=\"btn btn-sm btn-outline-primary add-formset-row\"\n");
                    html.append("                                        data-formset-prefix=\"").append(formsetVar).append("\">\n");
                    html.append("                                    <i class=\"fas fa-plus\"></i> Add More\n");
                    html.append("                                </button>\n");
                    html.append("                            </div>\n");
                    html.append("                            \n");
                    html.append("                            {{ ").append(formsetVar).append(".management_form }}\n");
                    html.append("                            \n");
                    html.append("                            <div id=\"id_").append(formsetVar).append("-forms\" class=\"formset-forms\">\n");
                    html.append("                                {% for form in ").append(formsetVar).append(" %}\n");
                    html.append("                                <div class=\"formset-form-item card mb-2\">\n");
                    html.append("                                    <div class=\"card-body\">\n");
                    html.append("                                        {{ form|crispy }}\n");
                    html.append("                                        {% if form.instance.pk %}\n");
                    html.append("                                            <div class=\"form-check mt-2\">\n");
                    html.append("                                                {{ form.DELETE }}\n");
                    html.append("                                                <label class=\"form-check-label text-danger\" for=\"{{ form.DELETE.id_for_label }}\">\n");
                    html.append("                                                    Delete this item\n");
                    html.append("                                                </label>\n");
                    html.append("                                            </div>\n");
                    html.append("                                        {% endif %}\n");
                    html.append("                                    </div>\n");
                    html.append("                                </div>\n");
                    html.append("                                {% endfor %}\n");
                    html.append("                            </div>\n");
                    html.append("                        </div>\n");
                    html.append("\n");
                }
                
                html.append("                        <!-- Form Buttons -->\n");
                html.append("                        <div class=\"form-actions mt-4\">\n");
                html.append("                            <button type=\"submit\" class=\"btn btn-success\">\n");
                html.append("                                <i class=\"fas fa-save\"></i> Save All\n");
                html.append("                            </button>\n");
                html.append("                            <a href=\"{% url '").append(parentModelName.toLowerCase()).append("_list' %}\" class=\"btn btn-secondary\">\n");
                html.append("                                <i class=\"fas fa-times\"></i> Cancel\n");
                                html.append("                            </a>\n");
                                html.append("                        </div>\n");
                html.append("                    </form>\n");
                html.append("                </div>\n");
                html.append("            </div>\n");
                html.append("        </div>\n");
                html.append("    </div>\n");
                html.append("</div>\n");
                html.append("{% endblock %}\n");
                html.append("\n");
                html.append("{% block extra_css %}\n");
                html.append("<style>\n");
                html.append("    .formset-section {\n");
                html.append("        border: 1px solid #dee2e6;\n");
                html.append("        border-radius: 5px;\n");
                html.append("        padding: 20px;\n");
                html.append("        background-color: #f8f9fa;\n");
                html.append("    }\n");
                html.append("    \n");
                html.append("    .formset-form-item {\n");
                html.append("        border-left: 4px solid #007bff;\n");
                html.append("    }\n");
                html.append("    \n");
                html.append("    .section-title {\n");
                html.append("        color: #495057;\n");
                html.append("        font-size: 1.2rem;\n");
                html.append("    }\n");
                html.append("    \n");
                html.append("    .section-header {\n");
                html.append("        padding-bottom: 10px;\n");
                html.append("        border-bottom: 2px solid #e9ecef;\n");
                html.append("    }\n");
                html.append("</style>\n");
                html.append("{% endblock %}\n");
                html.append("\n");
                html.append("{% block extra_js %}\n");
                html.append("<script>\n");
                html.append("document.addEventListener('DOMContentLoaded', function() {\n");
                html.append("    // Function to add new formset row\n");
                html.append("    function addFormsetRow(prefix) {\n");
                html.append("        const formsContainer = document.getElementById('id_' + prefix + '-forms');\n");
                html.append("        const totalForms = document.getElementById('id_' + prefix + '-TOTAL_FORMS');\n");
                html.append("        const formCount = parseInt(totalForms.value);\n");
                html.append("        \n");
                html.append("        // Get the first form as template\n");
                html.append("        const template = formsContainer.children[0].cloneNode(true);\n");
                html.append("        \n");
                html.append("        // Update all field names and IDs\n");
                html.append("        const regex = new RegExp('(' + prefix + '-\\\\d+-)', 'g');\n");
                html.append("        const newFormHtml = template.innerHTML.replace(regex, prefix + '-' + formCount + '-');\n");
                html.append("        \n");
                html.append("        // Create new div with updated HTML\n");
                html.append("        const newDiv = document.createElement('div');\n");
                html.append("        newDiv.className = 'formset-form-item card mb-2';\n");
                html.append("        newDiv.innerHTML = '<div class=\"card-body\">' + newFormHtml + '</div>';\n");
                html.append("        \n");
                html.append("        // Clear input values in the new form\n");
                html.append("        newDiv.querySelectorAll('input, select, textarea').forEach(function(input) {\n");
                html.append("            if (input.type !== 'hidden' && input.type !== 'checkbox') {\n");
                html.append("                input.value = '';\n");
                html.append("            }\n");
                html.append("            if (input.type === 'checkbox') {\n");
                html.append("                input.checked = false;\n");
                html.append("            }\n");
                html.append("        });\n");
                html.append("        \n");
                html.append("        // Remove DELETE checkbox from new form\n");
                html.append("        const deleteDiv = newDiv.querySelector('.form-check');\n");
                html.append("        if (deleteDiv) {\n");
                html.append("            deleteDiv.remove();\n");
                html.append("        }\n");
                html.append("        \n");
                html.append("        // Add new form to container\n");
                html.append("        formsContainer.appendChild(newDiv);\n");
                html.append("        totalForms.value = formCount + 1;\n");
                html.append("    }\n");
                html.append("    \n");
                html.append("    // Add event listeners to all 'Add More' buttons\n");
                html.append("    document.querySelectorAll('.add-formset-row').forEach(function(button) {\n");
                html.append("        button.addEventListener('click', function() {\n");
                html.append("            const prefix = this.getAttribute('data-formset-prefix');\n");
                html.append("            addFormsetRow(prefix);\n");
                html.append("        });\n");
                html.append("    });\n");
                html.append("    \n");
                html.append("    // Form validation\n");
                html.append("    document.getElementById('multi-formset-form').addEventListener('submit', function(e) {\n");
                html.append("        // You can add custom validation here\n");
                html.append("        console.log('Form submitted with ' + {{ parentFormsets.size() }} + ' formsets');\n");
                html.append("    });\n");
                html.append("});\n");
                html.append("</script>\n");
                html.append("{% endblock %}\n");
                html.append("\n");
            }
        } else {
            html.append("<!-- No formsets configured -->\n");
            html.append("<!-- Configure formsets in the Android app first -->\n");
        }
        
        return html.toString();
    }
    
    public static String generateUrlsCode(JSONObject projectJson) throws JSONException {
        StringBuilder code = new StringBuilder();
        
        code.append("# urls.py - URLs for Formsets\n");
        code.append("# Auto-generated by Django Generator Android App\n");
        code.append("\n");
        code.append("from django.urls import path\n");
        code.append("from . import views\n");
        code.append("\n");
        code.append("app_name = 'your_app_name'  # Change this to your app name\n");
        code.append("\n");
        code.append("urlpatterns = [\n");
        
        Set<String> generatedUrls = new HashSet<>();
        
        if (projectJson.has("formsets")) {
            JSONArray formsets = projectJson.getJSONArray("formsets");
            
            // Collect unique parent models
            for (int i = 0; i < formsets.length(); i++) {
                JSONObject formset = formsets.getJSONObject(i);
                String parentModelName = formset.getString("parent_model_name").toLowerCase();
                
                if (!generatedUrls.contains(parentModelName)) {
                    code.append("    # ").append(parentModelName).append(" URLs\n");
                    code.append("    path('").append(parentModelName).append("/', views.").append(parentModelName).append("ListView.as_view(), name='").append(parentModelName).append("_list'),\n");
                    code.append("    path('").append(parentModelName).append("/create/', views.create_").append(parentModelName).append(", name='").append(parentModelName).append("_create'),\n");
                    code.append("    path('").append(parentModelName).append("/<int:pk>/', views.").append(parentModelName).append("DetailView.as_view(), name='").append(parentModelName).append("_detail'),\n");
                    code.append("    path('").append(parentModelName).append("/<int:pk>/update/', views.update_").append(parentModelName).append(", name='").append(parentModelName).append("_update'),\n");
                    code.append("    path('").append(parentModelName).append("/<int:pk>/delete/', views.").append(parentModelName).append("DeleteView.as_view(), name='").append(parentModelName).append("_delete'),\n");
                    code.append("\n");
                    
                    generatedUrls.add(parentModelName);
                }
            }
        }
        
        code.append("]\n");
        
        // Add suggested views if not exist
        code.append("\n");
        code.append("# Suggested class-based views (add to views.py if needed):\n");
        code.append("#\n");
        code.append("# from django.views.generic import ListView, DetailView, DeleteView\n");
        code.append("#\n");
        for (String model : generatedUrls) {
            String modelName = model.substring(0, 1).toUpperCase() + model.substring(1);
            code.append("# class ").append(modelName).append("ListView(ListView):\n");
            code.append("#     model = ").append(modelName).append("\n");
            code.append("#     template_name = '").append(model).append("/list.html'\n");
            code.append("#     context_object_name = '").append(model).append("_list'\n");
            code.append("#     paginate_by = 20\n");
            code.append("#\n");
            code.append("# class ").append(modelName).append("DetailView(DetailView):\n");
            code.append("#     model = ").append(modelName).append("\n");
            code.append("#     template_name = '").append(model).append("/detail.html'\n");
            code.append("#\n");
            code.append("# class ").append(modelName).append("DeleteView(DeleteView):\n");
            code.append("#     model = ").append(modelName).append("\n");
            code.append("#     template_name = '").append(model).append("/confirm_delete.html'\n");
            code.append("#     success_url = reverse_lazy('").append(model).append("_list')\n");
            code.append("#\n");
        }
        
        return code.toString();
    }
    
    public static String generateAdminCode(JSONObject projectJson) throws JSONException {
        StringBuilder code = new StringBuilder();
        
        code.append("# admin.py - Admin configuration for Formsets\n");
        code.append("# Auto-generated by Django Generator Android App\n");
        code.append("\n");
        code.append("from django.contrib import admin\n");
        code.append("from django.forms import inlineformset_factory\n");
        code.append("from .models import *\n");
        code.append("\n");
        
        if (projectJson.has("formsets")) {
            JSONArray formsets = projectJson.getJSONArray("formsets");
            
            // Group by parent model
            Map<String, List<JSONObject>> formsetsByParent = new HashMap<>();
            
            for (int i = 0; i < formsets.length(); i++) {
                JSONObject formset = formsets.getJSONObject(i);
                String parentModelName = formset.getString("parent_model_name");
                
                if (!formsetsByParent.containsKey(parentModelName)) {
                    formsetsByParent.put(parentModelName, new ArrayList<JSONObject>());
                }
                formsetsByParent.get(parentModelName).add(formset);
            }
            
            // Generate admin classes
            for (Map.Entry<String, List<JSONObject>> entry : formsetsByParent.entrySet()) {
                String parentModelName = entry.getKey();
                List<JSONObject> parentFormsets = entry.getValue();
                
                code.append("class ").append(parentModelName).append("Admin(admin.ModelAdmin):\n");
                code.append("    list_display = ['id', '__str__']  # Customize as needed\n");
                code.append("    list_filter = []  # Add fields for filtering\n");
                code.append("    search_fields = []  # Add fields for search\n");
                code.append("    \n");
                code.append("    # Inline formsets for related models\n");
                code.append("    inlines = [\n");
                
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    code.append("        ").append(childModelName).append("Inline,\n");
                }
                
                code.append("    ]\n");
                code.append("    \n");
                code.append("    fieldsets = (\n");
                code.append("        (None, {\n");
                code.append("            'fields': ()\n");
                code.append("        }),\n");
                code.append("    )\n");
                code.append("\n");
                
                // Generate inline classes
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    
                    code.append("class ").append(childModelName).append("Inline(admin.TabularInline):  # or admin.StackedInline\n");
                    code.append("    model = ").append(childModelName).append("\n");
                    code.append("    extra = ").append(formset.optInt("extra_fields", 1)).append("  # Empty forms\n");
                    code.append("    can_delete = ").append(formset.optBoolean("can_delete", true)).append("  # Allow deletion\n");
                    code.append("    max_num = ").append(formset.optInt("max_num", 10)).append("  # Maximum forms\n");
                    code.append("    \n");
                    code.append("    # Customize fields display\n");
                    code.append("    fields = ('__all__')  # Or specify fields\n");
                    code.append("    \n");
                    code.append("    # Optional: customize form\n");
                    code.append("    # form = ").append(childModelName).append("Form\n");
                    code.append("\n");
                }
                
                code.append("# Register models with admin\n");
                code.append("admin.site.register(").append(parentModelName).append(", ").append(parentModelName).append("Admin)\n");
                
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    code.append("admin.site.register(").append(childModelName).append(")\n");
                }
                
                code.append("\n");
            }
        }
        
        return code.toString();
    }
    
    public static String generateReadme(JSONObject projectJson) throws JSONException {
        StringBuilder readme = new StringBuilder();
        
        readme.append("# Django Formsets - Auto Generated\n");
        readme.append("\n");
        readme.append("This code was automatically generated by Django Generator Android App.\n");
        readme.append("\n");
        
        if (projectJson.has("formsets")) {
            JSONArray formsets = projectJson.getJSONArray("formsets");
            
            readme.append("## Generated Formsets\n");
            readme.append("\n");
            
            // Group by parent model
            Map<String, List<JSONObject>> formsetsByParent = new HashMap<>();
            
            for (int i = 0; i < formsets.length(); i++) {
                JSONObject formset = formsets.getJSONObject(i);
                String parentModelName = formset.getString("parent_model_name");
                
                if (!formsetsByParent.containsKey(parentModelName)) {
                    formsetsByParent.put(parentModelName, new ArrayList<JSONObject>());
                }
                formsetsByParent.get(parentModelName).add(formset);
            }
            
            for (Map.Entry<String, List<JSONObject>> entry : formsetsByParent.entrySet()) {
                String parentModelName = entry.getKey();
                List<JSONObject> parentFormsets = entry.getValue();
                
                readme.append("### ").append(parentModelName).append("\n");
                readme.append("\n");
                readme.append("**Parent Model:** `").append(parentModelName).append("`\n");
                readme.append("\n");
                readme.append("**Inline Formsets (").append(parentFormsets.size()).append("):**\n");
                readme.append("\n");
                
                for (JSONObject formset : parentFormsets) {
                    String childModelName = formset.getString("child_model_name");
                    int extra = formset.optInt("extra_fields", 1);
                    boolean canDelete = formset.optBoolean("can_delete", true);
                    String prefix = formset.optString("prefix", childModelName.toLowerCase());
                    
                    readme.append("1. **").append(childModelName).append("**\n");
                    readme.append("   - Extra forms: ").append(extra).append("\n");
                    readme.append("   - Can delete: ").append(canDelete ? "Yes" : "No").append("\n");
                    readme.append("   - Prefix: `").append(prefix).append("`\n");
                    readme.append("   - Relationship: `").append(formset.optString("relationship_name", "auto")).append("`\n");
                    readme.append("\n");
                }
                
                readme.append("**URLs:**\n");
                readme.append("- List: `/").append(parentModelName.toLowerCase()).append("/`\n");
                readme.append("- Create: `/").append(parentModelName.toLowerCase()).append("/create/`\n");
                readme.append("- Update: `/").append(parentModelName.toLowerCase()).append("/<id>/update/`\n");
                readme.append("- Delete: `/").append(parentModelName.toLowerCase()).append("/<id>/delete/`\n");
                readme.append("\n");
            }
            
            readme.append("## Installation Instructions\n");
            readme.append("\n");
            readme.append("1. Copy the generated code to your Django project:\n");
            readme.append("   - `views.py` → Your app's views.py\n");
            readme.append("   - `forms.py` → Your app's forms.py\n");
            readme.append("   - `urls.py` → Update your app's urls.py\n");
            readme.append("   - `admin.py` → Your app's admin.py (optional)\n");
            readme.append("   - Templates → Create directory `templates/model_name/`\n");
            readme.append("\n");
            readme.append("2. Make sure your models are properly defined in `models.py`\n");
            readme.append("\n");
            readme.append("3. Run migrations:\n");
            readme.append("   ```bash\n");
            readme.append("   python manage.py makemigrations\n");
            readme.append("   python manage.py migrate\n");
            readme.append("   ```\n");
            readme.append("\n");
            readme.append("4. Configure URLs in your project's main `urls.py`:\n");
            readme.append("   ```python\n");
            readme.append("   urlpatterns = [\n");
            readme.append("       path('admin/', admin.site.urls),\n");
            readme.append("       path('', include('your_app.urls')),\n");
            readme.append("   ]\n");
            readme.append("   ```\n");
            readme.append("\n");
            readme.append("## Features\n");
            readme.append("\n");
            readme.append("✅ Multiple inline formsets in single page\n");
            readme.append("✅ Dynamic form addition with JavaScript\n");
            readme.append("✅ Form validation\n");
            readme.append("✅ Delete capability for existing items\n");
            readme.append("✅ Bootstrap 5 styling\n");
            readme.append("✅ Crispy forms integration\n");
            readme.append("✅ Admin panel integration\n");
            readme.append("✅ Responsive design\n");
            readme.append("\n");
            readme.append("## Customization\n");
            readme.append("\n");
            readme.append("You can customize:\n");
            readme.append("- Form fields in `forms.py`\n");
            readme.append("- Template styling in HTML files\n");
            readme.append("- JavaScript behavior\n");
            readme.append("- Admin panel display\n");
            readme.append("- Validation rules\n");
        } else {
            readme.append("No formsets were configured.\n");
            readme.append("Use the Android app to create formsets first.\n");
        }
        
        return readme.toString();
    }
}